@startuml
left to right direction
actor NhanVien as "Nhân Viên"
actor QuanLy as "Quản Lý"
actor NguoiThamGiaUngTuyen as "Người Tham Gia Ứng Tuyển"
actor CongTyTuyenDung as "Công Ty Tuyển Dụng"
QuanLy --^ NhanVien
rectangle "Quản lý tài khoản" {
  NguoiThamGiaUngTuyen -- (Đổi mật khẩu)
  (Đổi mật khẩu) -- CongTyTuyenDung
  NhanVien -- (Đổi mật khẩu)
  NhanVien -- (Khoá quyền truy cập hệ thống của người dùng)
  NhanVien -- (Mở quyền truy cập hệ thống của người dùng)
  QuanLy -- (Mở quyền truy cập hệ thống Admin)
  QuanLy -- (Khoá quyền truy cập hệ thống Admin)

}

@enduml
