@startuml
left to right direction
actor NhanVien as "Nhân Viên"
actor QuanLy as "Quản Lý"
actor NguoiThamGiaUngTuyen as "Người Tham Gia Ứng Tuyển"
actor CongTyTuyenDung as "Công Ty Tuyển Dụng"
QuanLy --^ NhanVien
rectangle "Quản lý bài đăng tuyển dụng"{
    (Đăng bài tuyển dụng) -- CongTyTuyenDung 
    (Chỉnh sửa bài đăng tuyển dụng) -- CongTyTuyenDung  
    NguoiThamGiaUngTuyen -- (Xem thông tin bài đăng tuyển dụng)
    NhanVien -- (Xem thông tin bài đăng tuyển dụng)
    (Xem thông tin bài đăng tuyển dụng) -- CongTyTuyenDung
    (Xoá thông tin bài đăng) -- CongTyTuyenDung
    NhanVien -- (Xoá thông tin bài đăng)
    NguoiThamGiaUngTuyen -- (Quản lý bài đăng yêu thích)
    NguoiThamGiaUngTuyen -- (Theo dõi các bài đăng mới của công ty tuyển dụng)
    CongTyTuyenDung -- (Theo dõi thông tin truy cập bài đăng)
    (Báo cáo bài đăng) -- CongTyTuyenDung
    NguoiThamGiaUngTuyen -- (Báo cáo bài đăng)
}
@enduml