@startuml
left to right direction
actor NhanVien as "Nhân Viên"
actor QuanLy as "Quản Lý"
actor NguoiThamGiaUngTuyen as "Người Tham Gia Ứng Tuyển"
actor CongTyTuyenDung as "Công Ty Tuyển Dụng"
QuanLy --^ NhanVien
rectangle "Quản lý hồ sơ cá nhân"{
    (Tạo hồ sơ cá nhân) -- NguoiThamGiaUngTuyen
    (Chỉnh sửa hồ sơ công ty tuyển dụng) -- NguoiThamGiaUngTuyen
    (Xoá hồ sơ công ty tuyển dụng) -- NguoiThamGiaUngTuyen
    NhanVien -- (Xoá hồ sơ công ty tuyển dụng) 
    (Xem hồ sơ công ty tuyển dụng) -- NguoiThamGiaUngTuyen
    NhanVien -- (Xem hồ sơ công ty tuyển dụng)
    CongTyTuyenDung -- (Xem hồ sơ công ty tuyển dụng)
    NhanVien -- (Kiểm duyệt hồ sơ người dùng)
    (Tìm kiếm hồ sơ người dùng) -- NguoiThamGiaUngTuyen
    NhanVien -- (Tìm kiếm hồ sơ người dùng)
    CongTyTuyenDung -- (Tìm kiếm hồ sơ người dùng)
    (Báo cáo hồ sơ cá nhân) -- NguoiThamGiaUngTuyen
    CongTyTuyenDung -- (Báo cáo hồ sơ cá nhân)
}
@enduml