@startuml DangNhap/DangKy
left to right direction
actor nhanVien as "Candidate"
actor quanLy as "Manager"
actor nguoiUngTuyen as "Candidate"
actor congTy as "Company"
quanLy --^ nhanVien
rectangle "Đăng nhập/Đăng ký" {
    usecase "Đăng nhập vào hệ thống" as dangNhap
    usecase "Đăng ký tài khoản" as dangKyTaiKhoan
    usecase "Quên mật khẩu" as quenMatKhau
}
nhanVien -- dangNhap

congTy -- dangNhap
congTy -- dangKyTaiKhoan
congTy -- quenMatKhau


dangNhap -- nguoiUngTuyen
dangKyTaiKhoan -- nguoiUngTuyen
quenMatKhau -- nguoiUngTuyen

@enduml
