@startuml DangNhap/DangKy
left to right direction
actor nhanVien as "Nhân Viên"
actor quanLy as "Quản Lý"
actor nguoiUngTuyen as "Người Ứng Tuyển"
actor congTy as "Công Ty Tuyển Dụng"
quanLy --^ nhanVien
rectangle "Đăng nhập/Đăng ký" {
    usecase "Đăng nhập vào hệ thống" as dangNhap
    usecase "Đăng ký tài khoản" as dangKyTaiKhoan
    usecase "Quên mật khẩu" as quenMatKhau
}
nhanVien -- dangNhap

congTy -- dangNhap
congTy -- dangKyTaiKhoan
congTy -- quenMatKhau


dangNhap -- nguoiUngTuyen
dangKyTaiKhoan -- nguoiUngTuyen
quenMatKhau -- nguoiUngTuyen

@enduml
