@startuml QuanLyUngTuyen
left to right direction

actor "Công ty\ntuyển dụng" as congTyTuyenDung

rectangle "Quản lý ứng tuyển" {
    usecase "Xem thông tin ứng tuyển" as xemThongTinUngTuyen
    usecase "Duyệt yêu cầu ứng tuyển" as duyetYeuCauUngTuyen
}

congTyTuyenDung -- xemThongTinUngTuyen
congTyTuyenDung -- duyetYeuCauUngTuyen

@enduml
```