@startuml NhanTin
left to right direction

actor "User" as nguoiDung
actor "Candidate" as nguoiUngTuyen
actor "Company" as congTyTuyenDung
actor "Staff" as nhanVien
actor "Manager" as quanLy

rectangle "Nhắn tin" {
    usecase "Gửi tin nhắn" as guiTinNhan
    usecase "Đọc tin nhắn" as docTinNhan
    usecase "Thu hồi tin nhắn" as thuHoiTinNhan
    usecase "Xóa tin nhắn" as xoaTinNhan
    usecase "Chặn tin nhắn" as chanTinNhan
    usecase "Bỏ chặn tin nhắn" as boChanTinNhan
}

nguoiDung -- guiTinNhan
nguoiDung -- docTinNhan
nguoiDung -- thuHoiTinNhan
nguoiDung -- xoaTinNhan
nguoiDung -- chanTinNhan
nguoiDung -- boChanTinNhan

nguoiUngTuyen --^ nguoiDung

congTyTuyenDung --^ nguoiDung

nhanVien --^ nguoiDung

quanLy --^ nhanVien

@enduml
