@startuml QuanLyPhanTichThongKe
left to right direction

actor "Quản lý" as quanLy
actor "Nhân viên" as nhanVien

rectangle "Quản lý phân tích thống kê" {
    usecase "Xem thống kê người ứng tuyển" as xemThongKeNguoiUngTuyen
    usecase "Xem thống kê công ty tuyển dụng" as xemThongKeCongTyTuyenDung
    usecase "Xem thống kê lượt truy cập hệ thống" as xemThongKeLuotTruyCapHeThong
    usecase "Xem phân tích xu hướng nghề nghiệp" as xemPhanTichXuHuongNgheNghiep
    usecase "Xem thống kê tỉ lệ xin việc" as xemThongKeTiLeXinViec
}

nhanVien -- xemThongKeNguoiUngTuyen
nhanVien -- xemThongKeCongTyTuyenDung
nhanVien -- xemThongKeLuotTruyCapHeThong
nhanVien -- xemPhanTichXuHuongNgheNghiep
nhanVien -- xemThongKeTiLeXinViec

quanLy --^ nhanVien

@enduml
