@startuml QuanLyTaiKhoan

left to right direction

actor "Manager" as quanLy

rectangle "Quản lý tài khoản" {
    usecase "Tạo tài khoản" as taoTaiKhoan
    usecase "Xem thông tin tài khoản" as xemThongTinTaiKhoan
    usecase "Cập nhật thông tin tài khoản" as capNhatThongTinTaiKhoan
    usecase "Xóa tài khoản" as xoaTaiKhoan
}

quanLy -- taoTaiKhoan
quanLy -- xemThongTinTaiKhoan
quanLy -- capNhatThongTinTaiKhoan
quanLy -- xoaTaiKhoan

@enduml
