@startuml QuanLyBaiDangTuyenDungCRUD
left to right direction
actor congTy as "Company"
actor nhanVien as "Staff"
actor nguoiUngTuyen as "Candidate"
rectangle "Quản lý bài đăng tuyển dụng (CRUD)"{
    usecase "Tạo bài đăng tuyển dụng" as taoBaiDangTuyenDung
    usecase "Truy cập bài đăng" as truyCapBaiDang
    usecase "Chỉnh sửa bài đăng" as chinhSuaBaiDang
    usecase "Xoá thông tin bài đăng" as xoaThongTinBaiDang
}
congTy -- taoBaiDangTuyenDung
congTy -- truyCapBaiDang
congTy -- chinhSuaBaiDang
congTy -- xoaThongTinBaiDang 
nguoiUngTuyen -- truyCapBaiDang
truyCapBaiDang -- nhanVien
