@startuml DanhGia
left to right direction
actor nguoiUngTuyen as "Candidate"
actor congTy as "Company"
rectangle "Đánh giá"{
    usecase danhGiaCongTyTuyenDung as "Đánh giá công ty tuyển dụng"
    usecase danhGiaNguoiTuyenDung as "Đánh giá người tuyển dụng"
}
nguoiUngTuyen -- danhGiaCongTyTuyenDung

congTy -- danhGiaNguoiTuyenDung
