@startuml QuanLyTaiKhoanCongTy
left to right direction
actor congTy as "Company"
rectangle "Quản lý tài khoản công ty"{
    usecase quanLyHoSoCongTy as "Quản lý hồ sơ công ty"
    usecase doiMatKhau as "Đổi mật khẩu"
}
congTy -- quanLyHoSoCongTy
congTy -- doiMatKhau