@startuml UngTuyen
left to right direction

actor "Người ứng tuyển" as nguoiUngTuyen

rectangle "Ứng tuyển" {
    usecase "Gửi yêu cầu ứng tuyển" as nopYeuCauUngTuyen
    usecase "Xem thông tin ứng tuyển" as xemTrangThaiYeuCauUngTuyen
}

nguoiUngTuyen -- nopYeuCauUngTuyen
nguoiUngTuyen -- xemTrangThaiYeuCauUngTuyen

@enduml
```