@startuml UngTuyen
left to right direction

actor "Người ứng tuyển" as nguoiUngTuyen

rectangle "Ứng tuyển" {
    usecase "Nộp yêu cầu ứng tuyển" as nopYeuCauUngTuyen
    usecase "Xem trạng thái yêu cầu ứng tuyển" as xemTrangThaiYeuCauUngTuyen
    usecase "Nhận thông báo kết quả ứng tuyển" as nhanThongBaoKetQuaUngTuyen
}

nguoiUngTuyen -- nopYeuCauUngTuyen
nguoiUngTuyen -- xemTrangThaiYeuCauUngTuyen
nguoiUngTuyen -- nhanThongBaoKetQuaUngTuyen

@enduml
```