@startuml QuanLyTaiKhoanAdmin
left to right direction
actor nhanVien as "Staff"

rectangle "Quản lý tài khoản admin"{
    usecase truyCapHoSoCaNhanAdmin as "Truy cập hồ sơ admin"
    usecase doiMatKhau as "Đổi mật khẩu"
}
nhanVien -- truyCapHoSoCaNhanAdmin
nhanVien -- doiMatKhau