@startuml SeqDangKy

skin rose
hide footbox

actor "Người ứng tuyển" as nguoiUngTuyen
boundary ":Signup Interface\nClass" as signupInterface
control ": Signup Controller\nClass" as signupControl
entity ": User\nClass" as user
autonumber
nguoiUngTuyen++    
nguoiUngTuyen -> signupInterface++ : Người dùng chọn đăng ký dưới dạng người tuyển dụng 
signupInterface -> signupInterface-- : Hiển thị trang đăng ký cho người ứng tuyển
nguoiUngTuyen -> signupInterface++: Nhập thông tin người dùng
signupInterface -> signupInterface: Kiểm tra format thông tin người dùng

alt Invalid Data
    signupInterface ->signupInterface--: Thông báo sai thông tin người dùng
else
    signupInterface -> signupControl++: Gửi thông tin cá nhân
    signupControl -> signupInterface++: Gửi mã xác thực về cho người dùng
    nguoiUngTuyen -> signupInterface: Nhập mã xác thực 
    signupInterface -> signupControl: Kiểm tra mã xác thực
    alt Invalid OTP
        signupControl -> signupInterface : Thông báo sai mã OTP
    else
        signupControl -> user: Tạo tài khoản người tuyển dụng
        signupControl -> signupInterface: Thông báo tạo tài khoản thành công
    end
end
