@startuml SeqQuenMatKhau
skin rose
hide footbox
autonumber
actor user as "User"
boundary userInterface as ": User Interface\n Class"
control userController as ": User controller\nClass"
entity User as ": User\nClass"
user++
user -> userInterface++: Truy cập vào trang quên mật khẩu
userInterface -> userInterface: Hiển thị trang quên mật khẩu
user -> userInterface: Nhập username 
userInterface -> userInterface: Kiểm tra format username
alt Invalid Data
    userInterface -> user: Hiển thị thông báo\n"Sai format thông tin đăng nhập"
else Valid Data
    userInterface -> userController++: Gửi thông tin username
    userController -> User++: Gửi thông tin username
    User -> User: Kiểm tra thông tin username
    alt Invalid Data
        User->userController: Thông báo sai thông tin người dùng
        userController -> userInterface: Hiển thị thông báo\n"Không có người dùng này trong hệ thống"
    else Valid Data
        User->userController--: Thông báo đúng thông tin người dùng
        userController -> userInterface: Hiển thị xác thực người dùng
        user -> userInterface: Nhập mã OTP
        alt Invalid OTP
        userInterface -> user: Hiển thị thông báo\n"Sai mã OTP"
        else Valid OTP
        userInterface -> userInterface: Hiển thị trang đổi mật khẩu
        user -> userInterface: Nhập mật khẩu mới
        userInterface -> userController: Gửi mật khẩu mới
        userController -> User: Đổi mật khẩu
        User -> userController: Đổi mật khẩu thành công
        userController -> userInterface: Hiển thị thông báo \n"đổi mật khẩu thành công"
        userInterface -> user: Thông báo đổi mật khẩu thành công
        end
    end 
end
@enduml