@startuml SeqQuenMatKhau
skin rose
hide footbox
actor user as "User"
boundary forgotPassInterface as ": ForgotPassword Interface\nClass"
boundary loginInterface as ": Login Interface\n Class"
boundary authenticationInterface as ": Authentication Interface\n Class"
boundary changePassInterface as ": ChangePassword Interface\n Class"
boundary mainInterface as ": Main Interface\n Class"

control forgotPassController as ": ForgotPassword Controller\nClass"
entity User as ": User\nClass"
user++
user -> forgotPassInterface++: Truy cập vào trang quên mật khẩu
forgotPassInterface -> forgotPassInterface--: Hiển thị trang quên mật khẩu
user -> forgotPassInterface++: Nhập username 
forgotPassInterface -> forgotPassInterface--: Kiểm tra format username
alt Invalid Data
    forgotPassInterface -> forgotPassInterface++: Hiển thị thông báo\n"Sai format thông tin đăng nhập"
else Valid Data
    forgotPassInterface -> forgotPassController++: Gửi thông tin username
    forgotPassController -> User++: Gửi thông tin username
    User -> User--: Kiểm tra thông tin username
    alt InValid Data
        User->forgotPassController: Thông báo sai thông tin người dùng
        forgotPassController -> forgotPassInterface: Hiển thị thông báo\n"Không có người dùng này trong hệ thống"
    else Valid Data
        User->forgotPassController--: Thông báo đúng thông tin người dùng
        forgotPassController -> authenticationInterface++: Hiển thị xác thực người dùng
        user -> authenticationInterface: Nhập mã OTP
        alt Invalid OTP
        authenticationInterface -> authenticationInterface--: Hiển thị thông báo\n"Sai mã OTP"
        else
        authenticationInterface -> changePassInterface++: Hiển thị trang đổi mật khẩu
        user -> changePassInterface: Nhập mật khẩu mới
        changePassInterface -> mainInterface: Hiển thị trang chủ người dùng
        end
    end 
end
@enduml