@startuml SeqBoChanTinNhan

skin rose
hide footbox
title Bỏ chặn tin nhắn

actor User as user
boundary ": User Interface\nClass" as userInterface
control ": Chat Controller\nClass" as chatController
entity ": Chat\nClass" as chat

autonumber
user++
user -> userInterface++: Nhấn nút bỏ chặn tin nhắn
userInterface -> user: Gửi yêu cầu xác nhận
alt Không xác nhận bỏ chặn tin nhắn
    user -> userInterface: Nhấn nút hủy
    userInterface -> user: Hiển thị giao diện nhắn tin cũ
else Xác nhận bỏ chặn tin nhắn
    autonumber 3
    user -> userInterface: Nhấn nút xác nhận
    userInterface -> chatController++: Gửi yêu cầu bỏ chặn tin nhắn
    chatController -> chat++: Chặn tin nhắn
    chat -> chatController--: Trả về thông báo \nvà cuộc trò chuyện mới
    chatController -> userInterface--: Trả về thông báo\nvà cuộc trò chuyện mới
    userInterface -> user--: Hiển thị thông báo\nvà giao diện nhắn tin mới
end
user--

@enduml