@startuml SeqmanagerTruyCapHeThong

skin rose
hide footbox

title Quản lý truy cập hệ thống

actor "Manager" as manager
boundary ": Admin Interface\nClass" as adminInterface
control ": Manage User\nClass" as manageUser
entity ": User\nClass" as user

autonumber
manager++
manager -> adminInterface++ : Truy cập giao điện quản lý người dùng
adminInterface -> manageUser++ : Yêu cầu danh sách người dùng
manageUser -> user++ : Lấy danh sách người dùng
user -> manageUser-- : Trả về danh sách người dùng
manageUser -> adminInterface-- : Trả về danh sách người dùng
adminInterface -> manager-- : Hiển thị danh sách người dùng
manager -> adminInterface++ : Truy cập giao diện thông tin người dùng
adminInterface -> manager-- : Hiển thị giao diện thông tin người dùng

opt Actor choice: Khóa quyền truy cập hệ thống
    manager -> adminInterface++ : Chọn chức năng khóa quyền truy cập hệ thống
    adminInterface -> manager : Gửi yêu cầu xác nhận hành động
    alt Actor choice: Không xác nhận
        manager -> adminInterface : Không xác nhận
        adminInterface -> manager-- : Hiển thị giao diện thông tin người dùng
    else Actor choice: Xác nhận
        autonumber 11
        manager -> adminInterface++ : Xác nhận
        adminInterface -> manageUser++ : Yêu cầu khóa quyền truy cập hệ thống
        manageUser -> user++ : Khóa quyền truy cập hệ thống
        user -> manageUser-- : Trả về kết quả\nkhóa quyền truy cập hệ thống
        manageUser -> adminInterface-- : Trả về kết quả\nkhóa quyền truy cập hệ thống
        adminInterface -> manager-- : Hiển thị thông báo\nkết quả khóa quyền truy cập hệ thống
    end
end

opt Actor choice: Mở khóa quyền truy cập hệ thống
    autonumber 9
    manager -> adminInterface++ : Chọn chức năng mở khóa quyền truy cập hệ thống
    adminInterface -> manager : Gửi yêu cầu xác nhận hành động
    alt Không xác nhận
        manager -> adminInterface : Không xác nhận
        adminInterface -> manager-- : Hiển thị giao diện thông tin người dùng
    else xác nhận
        autonumber 11
        manager -> adminInterface++ : Xác nhận
        adminInterface -> manageUser++ : Yêu cầu mở khóa quyền truy cập hệ thống
        manageUser -> user++ : Mở khóa quyền truy cập hệ thống
        user -> manageUser-- : Trả về kết quả\nmở khóa quyền truy cập hệ thống
        manageUser -> adminInterface-- : Trả về kết quả\nmở khóa quyền truy cập hệ thống
        adminInterface -> manager-- : Hiển thị thông báo\nkết quả mở khóa quyền truy cập hệ thống
    end
end

manager--

@enduml
