@startuml SeqTruyCapBaiDang
skin rose
hide footbox

actor user
boundary postInterface as ": Post Interface\nClass"
control managePostController as ": Manage Post Controller\nClass"
entity Post as ": Post\nClass"
autonumber 
user++
user -> postInterface++: Truy cập vào trang bài đăng
postInterface-> managePostController++: Yêu cầu truy cập bài đăng
managePostController -> Post++:Gửi thông tin bài đăng cần truy cập
Post -> Post: Kiểm tra bài đăng trong dữ liệu
alt Post not exist
    Post-> managePostController: Thông báo không có\n bài đăng đó
    managePostController -> postInterface: Hiển thị trang \nbài đăng không tồn tại 
    postInterface -> user: Thông báo không có bài đăng này
else Post existed
    Post-> managePostController: Gửi toàn bộ thông tin bài đăng
    managePostController -> postInterface: Hiển thị trang bài đăng tuyển dụng với \ncác thông tin nhận được
    postInterface -> postInterface: Hiển thị trang web cho người dùng
end
@enduml