@startuml SeqCapNhatBaiDang
skin rose
hide footbox

actor congTy as "Công ty\ntuyển dụng"
boundary companyInterface as ": Company Interface\nClass"
entity Post as ": Post\nClass"
congTy++
control companyInterface as ": Manage Post Controller\nClass"
entity Post as ": Post\nClass"
autonumber 
congTy++
congTy -> companyInterface++: Truy cập vào trang bài đăng
companyInterface-> companyInterface: Yêu cầu truy cập bài đăng
companyInterface -> Post++:Gửi thông tin bài đăng cần truy cập
Post -> Post: Kiểm tra bài đăng trong dữ liệu
alt Post not exist
    Post-> companyInterface: Thông báo không có\n bài đăng đó
    companyInterface -> companyInterface: Hiển thị trang \nbài đăng không tồn tại 
    companyInterface -> congTy: Thông báo không có bài đăng này
else Post existed
    Post-> companyInterface: Gửi toàn bộ thông tin bài đăng
    companyInterface -> companyInterface: Hiển thị trang cập nhật bài đăng\n tuyển dụng với các thông tin nhận được
    companyInterface -> congTy: Hiển thị trang web cho công ty
    congTy-> companyInterface: Nhập thông tin mới\n của bài đăng
    companyInterface->companyInterface: Kiểm tra thông tin mới của bài đăng
    opt Accept Button
    alt Invalid data
    companyInterface -> companyInterface: Hiển thị thông bái \n"Thiếu hoặc sai thông tin bài đăng"
    else Valid data
    companyInterface -> companyInterface: Gửi yêu cầu cập nhật thông tin bài đăng
    companyInterface -> Post: Gửi thông tin bài đăng mới cập nhật
    Post -> companyInterface: Thông báo đã cập nhật thông tin bài đăng
    companyInterface -> companyInterface: Hiển thị thông báo\n"Cập nhật thông tin thành công"
    companyInterface -> congTy: Thông báo cho công ty đã cập nhật\n thành công bài đăng tuyển dụng
    end
    end
    opt Cancel Button
    companyInterface -> companyInterface: Thoát khỏi trang \ncập nhật thông tin bài đăng
    end
end
@enduml