@startuml SeqTheoDoiCongTyTuyenDung
skin rose 
hide footbox
actor nguoiUngTuyen as "Người ứng tuyển"
boundary companyInterface as ": Company Interface\nClass"
control manageCompanyController as ": Manage Company Controller\nClass"
entity Company as ": Company\nClass"
entity User as ": User\nClass"
nguoiUngTuyen++
autonumber
nguoiUngTuyen -> companyInterface++: Truy cập hồ sơ công ty
companyInterface -> manageCompanyController++: Gửi yêu cầu truy cập \nhồ sơ công ty tuyển dụng
manageCompanyController -> Company++: Gửi thông tin công ty
Company -> Company: Kiểm tra thông tin công ty 
alt Invalid Data
Company -> manageCompanyController: Thông báo sai thông tin
manageCompanyController-> companyInterface: Thông báo không tìm thấy\nthông tin công ty tuyển dụng
else Valid Data
Company -> manageCompanyController: Gửi toàn bộ thông tin \ncông ty tuyển dụng
manageCompanyController -> companyInterface: Hiển thị trang với các \nthông tin công ty tuyển dụng được gửi về
nguoiUngTuyen -> companyInterface: Nhấn nút follow công ty
companyInterface -> manageCompanyController: Gửi yêu cầu follow công ty
manageCompanyController -> User++: Gửi thông tin follow công ty
User -> User: Kiểm tra thông tin công ty đã follow
    alt Unfollow Company
        User -> manageCompanyController: thông báo đã follow\n công ty tuyển dụng
        manageCompanyController->companyInterface: Hiển thị đã follow \ncông ty tuyển dụng
    else Follow Company
        User -> manageCompanyController: thông báo đã huỷ follow\n công ty tuyển dụng
        manageCompanyController->companyInterface: Hiển thị không follow \ncông ty tuyển dụng
    end
end
@enduml