@startuml SeqDanhGiaCongTyTuyenDung
skin rose 
hide footbox
actor nguoiUngTuyen as "Người ứng tuyển"
actor congTy as "Công ty \n tuyển dụng"
nguoiUngTuyen++
boundary companyInterface as ": Company Interface\nClass"
boundary candidateInterface as ": User Interface\nClass"
control userController as ": User Controller\nClass"
entity User as ": User\nClass"
nguoiUngTuyen->candidateInterface++: Chọn đánh giá một công ty \nđã từng tham gia ứng tuyển
candidateInterface->candidateInterface: Hiển thị bảng đánh giá công ty
nguoiUngTuyen-> candidateInterface: Nhập thông tin đánh giá công ty
candidateInterface-> userController: Gửi yêu cầu đánh giá công ty
userController-> User: Gửi thông tin đánh giá công ty
User ->  userController++: Gửi thông báo đánh giá đến công ty
userController-> companyInterface++: Hiển thị thông tin đánh giá công ty đó
companyInterface -> congTy: Thông báo đánh giá công ty đó
@enduml