@startuml SeqDoiMatKhau
skin rose 
hide footbox
actor user 
boundary userInterface as ": User Interface\nClass"
control userController as ": User controller\nClass"
entity User as ": User\nClass"
autonumber
user++
user -> userInterface++: Truy cập vào trang đổi mật khẩu
userInterface-> userInterface: Hiển thị trang web đổi mật khẩu 
user -> userInterface: Nhập mật khẩu cũ và mật khẩu mới 
userInterface -> userInterface: Kiểm tra mật khẩu nhập vào 
alt Invalid Password
userInterface -> userInterface: Hiển thị thông báo "Mật khẩu không hợp lệ"
else Valid Password
userInterface -> userController++ : Gửi yêu cầu đổi mật khẩu
userController -> User++: Gửi thông tin mật khẩu cũ và mật khẩu mới
User -> User: Kiểm tra mật khẩu nhập vào 
alt Invalid Old Password
User -> userController: Thông báo sai mật khẩu cũ
userController -> userInterface: Hiển thị thông báo "Sai mật khẩu cũ"
else Valid Old Password
User -> User: Đổi mật khẩu
User -> userController: Thông báo đổi mật khẩu thành công
userController -> userInterface: Hiển thị thông báo "Đổi mật khẩu thành công"
userInterface -> user: Hiển thị thông báo đổi mật khẩu thành công
end
end
@enduml