@startuml SeqTruyCapHoSoCongTy
skin rose 
hide footbox
actor congTy as "Công ty tuyển dụng"
boundary companyInterface as ": Company Interface\nClass"
control userController as ": User Controller\nClass"
entity User as ": User\nClass"
congTy++
autonumber
congTy -> companyInterface++: Truy cập vào hồ sơ công ty tuyển dụng
companyInterface -> userController++: Gửi yêu cầu truy cập hồ sơ công ty tuyển dụng
userController -> User++: Đưa thông tin tài khoản công ty tuyển dụng
User -> userController: Toàn bộ thông tin tài khoản công ty tuyển dụng 
userController -> companyInterface: Hiển thị toàn bộ thông tin người dùng congTy
companyInterface -> congTy: Hiển thị thông tin công ty tuyển dụng
@enduml