@startuml SeqTimKiem(company)

skin rose
hide footbox

title Tìm kiếm (Công ty tuyển dụng)

actor Company as company
boundary ": Company Interface\nClass" as companyInterface
control ": Search Controller\nClass" as searchController
control ": Company Controller\nClass" as companyController
control ": Candidate Controller\nClass" as candidateController
control ": Post Controller\nClass" as postController
entity ": Company\nClass" as companyClass
entity ": Candidate\nClass" as candidateClass
entity ": Post\nClass" as postClass

autonumber
company++
company -> companyInterface++: Nhập từ khóa
companyInterface -> searchController++: Truyền từ khóa
par
    searchController -> companyController++: Yêu cầu thông tin công ty có từ khóa
    companyController -> companyClass++: Lấy thông tin công ty có từ khóa
    companyClass --> companyController--: Trả về thông tin công ty có từ khóa
    companyController --> searchController--: Trả về thông tin công ty có từ khóa
else
    autonumber 3
    searchController -> candidateController++: Yêu cầu thông tin người ứng tuyển có từ khóa
    candidateController -> candidateClass++: Lấy thông tin người ứng tuyển có từ khóa
    candidateClass --> candidateController--: Trả về thông tin người ứng tuyển có từ khóa
    candidateController --> searchController--: Trả về thông tin người ứng tuyển có từ khóa
else
    autonumber 3
    searchController -> postController++: Yêu cầu thông tin bài viết có từ khóa
    postController -> postClass++: Lấy thông tin bài viết có từ khóa
    postClass --> postController--: Trả về thông tin bài viết có từ khóa
    postController --> searchController--: Trả về thông tin bài viết có từ khóa
end
searchController --> companyInterface--: Trả về kết quả tìm kiếm
companyInterface --> company--: Hiển thị kết quả tìm kiếm
company--
@enduml