@startuml ActQuenMatKhau
skin rose
title Quên mật khẩu
|User|
start
: Ấn vào nút quên mật khâut\n;
|System|
: Hiển thị trang nhập username;
|User|
repeat : Nhập thông tin tài khoản\n lấy lại mật khẩu;
: Ấn nút gửi mã xác thực;
|System|
: Kiểm tra format thông tin đăng nhập;
backward :Hiển thị thông báo lỗi thông tin username;
repeat while () is (Invalid data) not (Valid data) 
|Database|
:Kiểm tra thông tin tài khoản;
if () then (Invalid data)
    |System|
    : Hiển thị thông báo sai thông tin tài khoản;
    stop
else (Valid data)
    |System|
    : Thông báo kiểm tra tài khoản thành công\n và gửi mã OTP về email;
    |User|
    repeat : Nhập mã OTP nhận được;
    : Ấn nút xác thực OTP;
    |System|
    : Kiểm tra mã OTP
    backward: Thông báo sai mã OTP;
    repeat while () is (Invalid OTP) not (Valid OTP)
    |System|
    : Hiển thị trang cập nhật mật khẩu mới;
    |User|
    repeat: Nhập mật khẩu mới của tài khoản;;
    : Ấn nút cập nhật mật khẩu;
    |System|
    : Kiểm tra mật khẩu đã nhập;
    backward :Hiển thị thông báo lỗi \nthông tin mật khẩu mới;
    repeat while () is (Invalid password) not (Valid password) 
    |Database|
    : Cập nhật mật khẩu mới cho tài khoản;
    |System|
    : Thông báo cập nhật mật khẩu thành công;
    stop


    


