@startuml ActThuHoiTinNhan

skin rose
title Thu hồi tin nhắn

|User|
start 
: Chọn tin nhắn;
: Nhấn nút thu hồi tin nhắn;
|System|
: Yêu cầu xác nhận;
|User|
if () then (Không xác nhận)
: Không xác nhận;
stop
else (Xác nhận)
|User|
: Xác nhận;
|System|
: Cập nhật cuộc trò chuyện;
|Database|
: Thay thế tin nhắn\nbằng tin nhắn thu hồi;
: Trả về cuộc trò chuyện mới;
|System|
: Hiển thị cuộc trò chuyện mới;
stop
@enduml
```