@startuml ActTimKiem(Manager)

skin rose
title Tìm kiếm (Quản lý)

|Manager|
start
: Nhập từ khóa;
: Nhấn nút tìm kiếm;
|System|
: Tìm kiếm;
|Database|
split
: Truy vấn dữ liệu\nngười dùng liên quan;
split again
: Truy vấn dữ liệu\nbài viết liên quan;
end split
: Trả về kết quả tìm kiếm;
|System|
: Hiển thị kết quả tìm kiếm;
stop

@enduml