@startuml ActTruyCapHoSoCongTyTuyenDung

skin rose
title Truy cập hồ sơ công ty tuyển dụng

|User|
start
: Truy cập giao diện\nhồ sơ công ty tuyển dụng;
|System|
: Lấy thông tin hồ sơ\ncông ty tuyển dụng;
|Database|
: Truy vấn dữ liệu;
: Trả về thông tin hồ sơ\ncông ty tuyển dụng;
|System|
: Hiển thị thông tin\nhồ sơ công ty tuyển dụng;
stop

@enduml
```