@startuml ActTruyCapBaiDangCongTy

skin rose
title Truy cập bài đăng công ty

|Company|
start
: 1. Truy cập giao diện bài đăng;
|System|
: 2. Lấy thông tin bài đăng;
|Database|
: 3. Truy vấn thông tin bài đăng;
: 4. Trả về thông tin bài đăng;
|System|
: 5. Hiển thị thông tin bài đăng;
stop
@enduml
