@startuml ActBaoCaoBaiDang
skin rose
title Báo cáo bài đăng
|User|
start
: User truy cập trang bài đăng;
|System|
: Hiển thị trang bài đăng;
|User|
: Ấn nút báo cáo bài đăng;
: Nhập thông tin báo cáo bài đăng;
|System|
: Gửi thông tin báo cáo bài đăng;
|Database|
: Gửi thông tin bài đăng bị báo cáo;
|System|
: Trả về thông tin đã tố cáo bài đăng thành công;
|User|
: Hiển thị thông tin \n"Chúng tôi đã nhận được báo cáo của bạn" ;

stop

@enduml