@startuml ActBaoCaoCongTyTuyenDung
skin rose
title Báo cáo công ty tuyển dụng
|User|
start
: 1. User truy cập trang công ty tuyển dụng;
|System|
: 2. Hiển thị trang công ty tuyển dụng;
|Admin/User|
: 3. Ấn nút báo cáo công ty tuyển dụng;
: 4. Nhập thông tin báo cáo công ty tuyển dụng;
|System|
: 5. Gửi thông tin báo cáo công ty tuyển dụng;
|Database|
: 6. Gửi thông tin công ty tuyển dụng bị báo cáo;
|System|
: 7. Hiển thị thông tin công ty \n tuyển dụng bị báo cáo về phía admin;
|Admin/User|
: 8. Kiểm duyệt bản báo cáo công ty tuyển dụng;
: 9. Chọn biện pháp xử lý bản báo cáo;
if () then (Cancel Report)
: 10.1. Chọn huỷ báo cáo công ty tuyển dụng đó;
stop
else (Accept Report)
: 10.2. Chọn nút xác nhận báo cáo đúng thông tin;
|System|
: 11. Hiển thị phương pháp cảnh báo công ty tuyển dụng;
if () then (Ban Company Account)
|Database|
: 12.1. Cập nhật thông tin công ty \ntuyển dụng đã bị khoá hoạt động bởi admin;
|System|
: 13.1 Hiển thị công ty \ntuyển dụng đã bị khoá;
stop
else (Warning Company Account)
|Database|
: 12.2. Gửi thông tin cảnh báo\n công ty tuyển dụng\ntừ admin;
|System|
: 13.2. Hiển thị cảnh báo công ty\n tuyển dụng ở phía công ty tuyển dụng;
stop

@enduml