@startuml ActBaoCaoCongTyTuyenDung
skin rose
title Báo cáo công ty tuyển dụng
|User|
start
: User truy cập trang công ty tuyển dụng;
|System|
: Hiển thị trang công ty tuyển dụng;
|User|
: Ấn nút báo cáo công ty tuyển dụng;
: Nhập thông tin báo cáo công ty tuyển dụng;
|System|
: Gửi thông tin báo cáo công ty tuyển dụng;
|Database|
: Gửi thông tin công ty tuyển dụng bị báo cáo;
|System|
: Trả về thông tin đã tố cáo công ty tuyển dụng thành công;
|User|
: Hiển thị thông tin \n"Chúng tôi đã nhận được báo cáo của bạn" ;

stop

@enduml