@startuml ActBaoCaoBaiDang
skin rose
title Báo cáo người ứng tuyển
|Admin/User|
start
: User truy cập trang người ứng tuyển;
|System|
: Hiển thị trang người ứng tuyển;
|Admin/User|
: Ấn nút báo cáo người ứng tuyển;
: Nhập thông tin báo cáo người ứng tuyển;
|System|
: Gửi thông tin báo cáo người ứng tuyển;
|Database|
: Gửi thông tin người ứng tuyển bị báo cáo;
|System|
: Hiển thị thông tin người \n ứng tuyển bị báo cáo về phía admin;
|Admin/User|
: Kiểm duyệt bản báo cáo người ứng tuyển;
: Chọn biện pháp xử lý bản báo cáo;
if () then (Cancel Report)
: Chọn huỷ báo cáo người ứng tuyển đó;
stop
else (Accept Report)
: Chọn nút xác nhận báo cáo đúng thông tin;
|System|
: Hiển thị phương pháp cảnh báo người ứng tuyển;
if () then (Ban Candidate Account)
|Database|
: Cập nhật thông tin người \n ứng tuyển đã bị khoá hoạt động bởi admin;
|System|
: Hiển thị người ứng tuyển đã bị khoá;
stop
else (Warning Candidate Account)
|Database|
: Gửi thông tin cảnh báo\n người ứng tuyển từ admin;
|System|
: Hiển thị cảnh báo người \n ứng tuyển ở phía người ứng tuyển;
stop

@enduml
```