@startuml ActBaoCaoBaiDang
skin rose
title Báo cáo người ứng tuyển
|User|
start
: User truy cập trang người ứng tuyển;
|System|
: Hiển thị trang người ứng tuyển;
|User|
: Ấn nút báo cáo người ứng tuyển;
: Nhập thông tin báo cáo người ứng tuyển;
|System|
: Gửi thông tin báo cáo người ứng tuyển;
|Database|
: Gửi thông tin người ứng tuyển bị báo cáo;
|System|
: Trả về thông tin đã tố cáo người ứng tuyển thành công;
|User|
: Hiển thị thông tin \n"Chúng tôi đã nhận được báo cáo của bạn" ;

stop

@enduml