@startuml ActQuanLyHoSoCaNhan
title Cập nhật hồ sơ cá nhân
skin rose
|Candidate|
start
: Truy cập giao diện thông tin hồ sơ cá nhân;
|System|
: Lấy thông tin hồ sơ cá nhân;
|Database|
: Truy vấn thông tin hồ sơ cá nhân;
: Trả về thông tin hồ sơ cá nhân;
|System|
: Hiển thị thông tin hồ sơ cá nhân;
|Candidate|
: Chọn nút ở thông tin hồ sơ;
if () then (Back button)
|Candidate|
: Chọn chỉnh sửa thông tin cá nhân;
|System|
: Hiển thị trang chỉnh sửa thông tin cá nhân;
|Candidate|
repeat: Nhập thông tin cá nhân mới cần chỉnh sửa;
: Ân nút cập nhât thông tin;
|System|
backward :Thông báo sai thông tin nhập vào;
repeat while () is (Invalid data) not (Valid data)
|Database|
:Cập nhật thông tin cá nhân vừa nhập;
|System|
:Thông báo cập nhật thông tin cá nhân thành công;
stop
else
: Chọn nút quay về;
|System|
: Tắt trang thông tin cá nhân;
stop
@enduml