@startuml ActQuanLyHoSoAdmin
title Cập nhật hồ sơ admin
skin rose
|Admin|
start
: 1. Truy cập giao diện thông tin hồ sơ admin;
|System|
: 2. Lấy thông tin hồ sơ admin;
|Database|
: 3. Truy vấn thông tin hồ sơ admin;
: 4. Trả về thông tin hồ sơ admin;
|System|
: 5. Hiển thị thông tin hồ sơ admin;
|Admin|
: 6. Chọn nút ở thông tin hồ sơ;
if () then (Back button)
|Admin|
: 7.1 Chọn chỉnh sửa thông tin hồ sơ admin;
|System|
:  Hiển thị trang chỉnh sửa thông tin hồ sơ admin;
|Admin|
repeat: 9. Nhập thông tin hồ sơ admin mới cần chỉnh sửa;
: 10. Ân nút cập nhât thông tin;
|System|
backward : 10.1 Thông báo sai thông tin nhập vào;
repeat while () is (Invalid data) not (Valid data)
|Database|
:10.2 Cập nhật thông tin hồ sơ admin vừa nhập;
|System|
:11. Thông báo cập nhật thông tin hồ sơ admin thành công;
stop
else
:7.2 Chọn nút quay về;
|System|
:8. Tắt trang thông tin hồ sơ admin;
stop
@enduml