@startuml ActNopYeuCauUngTuyen

skin rose
title Nộp yêu cầu ứng tuyển

|Candidate|
start
: 1. Ấn vào nút\nứng tuyển;
|System|
: 2. Yêu cầu xác nhận\nứng tuyển;
|Candidate|
if () then (Không xác nhận)
: 3.1. Không xác nhận;
stop
else (Xác nhận)
|Candidate|
: 3.2. Xác nhận;
|System|
: 4. Kiểm tra bài đăng\ncó tồn tại;
|Database|
: 5. Truy vấn bài đăng;
if () then (Không tồn tại)
: 6.1. Trả về thông báo lỗi;
|System|
: 7.1. Hiển thị thông báo lỗi\nbài đăng không tồn tại;
stop
else (Tồn tại)
|Database|
: 6.2. Trả về thông báo\nbài đăng tồn tại;
|System|
: 7.2. Tạo ứng tuyển;
|Database|
: 8. Lưu thông tin\nứng tuyển;
: 9. Trả về thông báo\nứng tuyển thành công;
|System|
: 10. Hiển thị thông báo\nứng tuyển thành công;
stop

@enduml