@startuml ActChanTinNhan

skin rose
title Chặn tin nhắn

|User|
start 
: 1. Chọn cuộc trò chuyện;
: 2. Nhấn nút chặn tin nhắn;
|System|
: 3. Yêu cầu xác nhận chặn tin nhắn;
|User|
if () then (Không xác nhận)
: 4.1 Không xác nhận;
stop
else (Xác nhận)
: 4.2 Xác nhận;
|System|
: 5. Cập nhật cuộc trò chuyện;
|Database|
: 6. Trả về cuộc trò chuyện mới;
|System|
: 7. Hiển thị giao diện nhắn tin mới;
stop
@enduml