@startuml ActTruyCapBaiDang

skin rose
title Truy cập bài đăng

|User|
start
: 1. Truy cập giao diện\nbài đăng;
|System|
: 2. Lấy thông tin bài đăng;
|Database|
: 3. Truy vấn dữ liệu;
: 4. Trả về thông tin bài đăng;
|System|
: 5. Hiển thị thông tin bài đăng;
stop

@enduml