@startuml ActTruyCapHoSoNguoiUngTuyen

skin rose
title Truy cập hồ sơ người ứng tuyến

|User|
start
: 1. Truy cập giao diện\nhồ sơ người ứng tuyển;
|System|
: 2. Lấy thông tin hồ sơ\nngười ứng tuyển;
|Database|
: 3. Truy vấn dữ liệu;
: 4. Trả về thông tin hồ sơ\nngười ứng tuyển;
|System|
: 5. Hiển thị thông tin\nhồ sơ người ứng tuyển;
stop

@enduml