@startuml ActTaoTaiKhoan

skin rose
title Tạo tài khoản

|Manager|
|System|
|Database|

|Manager|
start
: 1. Truy cập giao diện quản lý tài khoản;
|System|
: 2. Hiển thị giao diện quản lý tài khoản;
|Manager|
: 3. Ấn nút tạo tài khoản và nhập thông tin tài khản;
|System|
: 4. Yêu cầu xác nhận tạo tài khoản;
|Manager|
if () then (Không xác nhận)
: 5.1. Không xác nhận;
stop
else (Xác nhận)
: 5.2. Xác nhận;
|System|
: 6. Yêu cầu tạo tài khoản;
|Database|
: 7. Tạo tài khoản;
: 8. Trả về kết quả tạo tài khoản;
|System|
: 9. Hiển thị thông báo tạo tài khoản thành công;
stop

@enduml