@startuml ClassDiagram

hide circle
skin rose

class Account {
    accountID
    accountName
    accountType
    accountPassword
    accountStatus
    accountDateCreated
    accountDateUpdated
    createAccount()
    getAccountInformation()
    updateAccount()
    deleteAccount()
}

class User {
    userID
    accountID
    userAvatar
    listChat
    createUser()
    getUserInformation()
    updateUserInformation()
}

class Admin {
    adminFirstName
    adminLastName
    getUserInformation()
    updateUserInformation()
}

class Candidate {
    candidateFirstName
    candidateLastName
    candidateDateOfBirth
    candidateGender
    candidatePhoneNumber
    candidateAddress
    candidateDescription
    candidateDateCreated
    cvID
    isReported
    listRating
    listJobApplication
    listFollowing
    getUserInformation()
    updateUserInformation()
}

class Company {
    companyName
    companyIncoporationDate
    companyAddress
    companyDescription
    companyLogo
    companyWebsite
    companyEmail
    companyPhone
    companyFollowersNumber
    isReported
    listRating
    listPost
    listJobApplication
    getUserInformation()
    updateUserInformation()
}

class Staff {

}

class Manager {

}

class Post {
    postID
    postTitle
    postDescription
    dateCreated
    dateUpdated
    postAuthor
    postViews
    postLikes
    postDislikes
    postImage
    createPost()
    getPostInformation()
    updatePost()
    deletePost()
}

class CandidateCV {
    cvID
    cvTitle
    cvDescription
    cvAuthor
    createCV()
    getCVInformation()
    updateCV()
    deleteCV()
}

class JobApplication {
    jobApplicationID
    jobApplicationTitle
    jonbApplicationDescription
    candidateID
    companyID
    createJobApplication()
    getJobApplicationInformation()
    updateJobApplication()
    deleteJobApplication()
}

class Chat {
    chatID
    userID
    chatStatus
    listMessage
    createChat()
    getChatInformation()
    updateChat()
    deleteChat()
}

class Message {
    messageID
    messageContent
    timestamp
    messageAuthor
    isRecalled
    createMessage()
    getMessageInformation()
    updateMessage()
    deleteMessage()
}

class AnalyticsAndStatistics {
    analyticsAndStatisticsID
    analyticsAndStatisticsTitle
    analyticsAndStatisticsDescription
    createAnalyticsAndStatistics()
    getAnalyticsAndStatisticsInformation()
    updateAnalyticsAndStatistics()
    deleteAnalyticsAndStatistics()
}

Account "1" --* "1" User: owns <
Admin --|> User
User <|-right- Candidate
User <|-- Company
Staff --|> Admin
Manager --|> Admin
AnalyticsAndStatistics "n" -- "1" Admin: manages <
Manager "1" -- "n" Account: manages >
Post "n" -right-* "1" Company: manages <
Chat "n" -right-* "2" User: manages <
Message "n" -right-* "1" Chat: haves <
CandidateCV "n" -left-* "1" Candidate: owns <
JobApplication "n" -left-* "1" Company: manages <
Candidate "n" -- "n" Company: follows >
Candidate "1" *-- "n" JobApplication: applies >

@enduml